"""empty message

Revision ID: 956c5b5698ed
Revises: ea3251a14ae0
Create Date: 2020-10-20 22:41:59.599769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956c5b5698ed'
down_revision = 'ea3251a14ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
